### ISSUE TITLE
PHP Fatal error:  Call to a member function request() on a non-object in Codeception/Module/REST.php on line 381

### ISSUE THREAD

**Issue by pantaovay** [Codeception/Codeception#1354]
PHP Fatal error:  Call to a member function request() on a non-object in phar:///vagrant_data/xueba/codecept.phar/src/Codeception/Module/REST.php on line 381
PHP Stack trace:
PHP   1. {main}() /vagrant_data/xueba/codecept.phar:0
PHP   2. require_once() /vagrant_data/xueba/codecept.phar:7
PHP   3. Symfony\Component\Console\Application->run() phar:///vagrant_data/xueba/codecept.phar/codecept:34
PHP   4. Symfony\Component\Console\Application->doRun() phar:///vagrant_data/xueba/codecept.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:124
PHP   5. Symfony\Component\Console\Application->doRunCommand() phar:///vagrant_data/xueba/codecept.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:193
PHP   6. Symfony\Component\Console\Command\Command->run() phar:///vagrant_data/xueba/codecept.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:887
PHP   7. Codeception\Command\Run->execute() phar:///vagrant_data/xueba/codecept.phar/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:252
PHP   8. Codeception\Codecept->run() phar:///vagrant_data/xueba/codecept.phar/src/Codeception/Command/Run.php:149
PHP   9. Codeception\Codecept->runSuite() phar:///vagrant_data/xueba/codecept.phar/src/Codeception/Codecept.php:145
PHP  10. Codeception\SuiteManager->run() phar:///vagrant_data/xueba/codecept.phar/src/Codeception/Codecept.php:162
PHP  11. Codeception\PHPUnit\Runner->doEnhancedRun() phar:///vagrant_data/xueba/codecept.phar/src/Codeception/SuiteManager.php:153
PHP  12. PHPUnit_Framework_TestSuite->run() phar:///vagrant_data/xueba/codecept.phar/src/Codeception/PHPUnit/Runner.php:100
PHP  13. PHPUnit_Framework_TestCase->run() phar:///vagrant_data/xueba/codecept.phar/vendor/phpunit/phpunit/src/Framework/TestSuite.php:675
PHP  14. PHPUnit_Framework_TestResult->run() phar:///vagrant_data/xueba/codecept.phar/vendor/phpunit/phpunit/src/Framework/TestCase.php:758
PHP  15. PHPUnit_Framework_TestCase->runBare() phar:///vagrant_data/xueba/codecept.phar/vendor/phpunit/phpunit/src/Framework/TestResult.php:686
PHP  16. PHPUnit_Framework_TestCase->runTest() phar:///vagrant_data/xueba/codecept.phar/vendor/phpunit/phpunit/src/Framework/TestCase.php:822
PHP  17. ReflectionMethod->invokeArgs() phar:///vagrant_data/xueba/codecept.phar/vendor/phpunit/phpunit/src/Framework/TestCase.php:956
PHP  18. Codeception\TestCase\Cept->testCodecept() phar:///vagrant_data/xueba/codecept.phar/vendor/phpunit/phpunit/src/Framework/TestCase.php:956
PHP  19. require() phar:///vagrant_data/xueba/codecept.phar/src/Codeception/TestCase/Cept.php:64
PHP  20. ApiTester->sendGET() /vagrant_data/xueba/tests/api/search/TopicCept.php:12
PHP  21. Codeception\Scenario->runStep() /vagrant_data/xueba/tests/api/ApiTester.php:1754
PHP  22. Codeception\TestCase\Cept->runStep() phar:///vagrant_data/xueba/codecept.phar/src/Codeception/Scenario.php:93
PHP  23. Codeception\Step->run() phar:///vagrant_data/xueba/codecept.phar/src/Codeception/TestCase/Shared/Actor.php:67
PHP  24. call_user_func_array:{phar:///vagrant_data/xueba/codecept.phar/src/Codeception/Step.php:125}() phar:///vagrant_data/xueba/codecept.phar/src/Codeception/Step.php:125
PHP  25. Codeception\Module\REST->sendGET() phar:///vagrant_data/xueba/codecept.phar/src/Codeception/Step.php:125
PHP  26. Codeception\Module\REST->execute() phar:///vagrant_data/xueba/codecept.phar/src/Codeception/Module/REST.php:257

Fatal error: Call to a member function request() on a non-object in phar:///vagrant_data/xueba/codecept.phar/src/Codeception/Module/REST.php on line 381

Call Stack:
    0.0193     695312   1. {main}() /vagrant_data/xueba/codecept.phar:0
    0.0413    1059456   2. require_once('phar:///vagrant_data/xueba/codecept.phar/codecept') /vagrant_data/xueba/codecept.phar:7
    0.2007    2906752   3. Symfony\Component\Console\Application->run() phar:///vagrant_data/xueba/codecept.phar/codecept:34
    0.2387    3239496   4. Symfony\Component\Console\Application->doRun() phar:///vagrant_data/xueba/codecept.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:124
    0.2397    3240384   5. Symfony\Component\Console\Application->doRunCommand() phar:///vagrant_data/xueba/codecept.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:193
    0.2398    3240856   6. Symfony\Component\Console\Command\Command->run() phar:///vagrant_data/xueba/codecept.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:887
    0.2457    3245560   7. Codeception\Command\Run->execute() phar:///vagrant_data/xueba/codecept.phar/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:252
    0.3626    5458672   8. Codeception\Codecept->run() phar:///vagrant_data/xueba/codecept.phar/src/Codeception/Command/Run.php:149
    0.3836    5465112   9. Codeception\Codecept->runSuite() phar:///vagrant_data/xueba/codecept.phar/src/Codeception/Codecept.php:145
    0.5908    9459016  10. Codeception\SuiteManager->run() phar:///vagrant_data/xueba/codecept.phar/src/Codeception/Codecept.php:162
    0.5993    9670152  11. Codeception\PHPUnit\Runner->doEnhancedRun() phar:///vagrant_data/xueba/codecept.phar/src/Codeception/SuiteManager.php:153
    0.6009    9698464  12. PHPUnit_Framework_TestSuite->run() phar:///vagrant_data/xueba/codecept.phar/src/Codeception/PHPUnit/Runner.php:100
    1.3537   11320136  13. PHPUnit_Framework_TestCase->run() phar:///vagrant_data/xueba/codecept.phar/vendor/phpunit/phpunit/src/Framework/TestSuite.php:675
    1.3541   11320136  14. PHPUnit_Framework_TestResult->run() phar:///vagrant_data/xueba/codecept.phar/vendor/phpunit/phpunit/src/Framework/TestCase.php:758
    1.3560   11320560  15. PHPUnit_Framework_TestCase->runBare() phar:///vagrant_data/xueba/codecept.phar/vendor/phpunit/phpunit/src/Framework/TestResult.php:686
    1.3586   11419768  16. PHPUnit_Framework_TestCase->runTest() phar:///vagrant_data/xueba/codecept.phar/vendor/phpunit/phpunit/src/Framework/TestCase.php:822
    1.3589   11420560  17. ReflectionMethod->invokeArgs() phar:///vagrant_data/xueba/codecept.phar/vendor/phpunit/phpunit/src/Framework/TestCase.php:956
    1.3589   11420592  18. Codeception\TestCase\Cept->testCodecept() phar:///vagrant_data/xueba/codecept.phar/vendor/phpunit/phpunit/src/Framework/TestCase.php:956
    1.3668   11431064  19. require('/vagrant_data/xueba/tests/api/search/TopicCept.php') phar:///vagrant_data/xueba/codecept.phar/src/Codeception/TestCase/Cept.php:64
    1.4877   11611472  20. ApiTester->sendGET() /vagrant_data/xueba/tests/api/search/TopicCept.php:12
    1.4877   11612208  21. Codeception\Scenario->runStep() /vagrant_data/xueba/tests/api/ApiTester.php:1754
    1.4877   11612296  22. Codeception\TestCase\Cept->runStep() phar:///vagrant_data/xueba/codecept.phar/src/Codeception/Scenario.php:93
    1.4886   11612952  23. Codeception\Step->run() phar:///vagrant_data/xueba/codecept.phar/src/Codeception/TestCase/Shared/Actor.php:67
    1.4886   11613440  24. call_user_func_array:{phar:///vagrant_data/xueba/codecept.phar/src/Codeception/Step.php:125}() phar:///vagrant_data/xueba/codecept.phar/src/Codeception/Step.php:125
    1.4887   11613776  25. Codeception\Module\REST->sendGET() phar:///vagrant_data/xueba/codecept.phar/src/Codeception/Step.php:125
    1.4887   11613960  26. Codeception\Module\REST->execute() phar:///vagrant_data/xueba/codecept.phar/src/Codeception/Module/REST.php:257

FATAL ERROR. TESTS NOT FINISHED.
Call to a member function request() on a non-object

**Comment by zbateson** [comment]
Should be fixed now with #1834

**Comment by tranfuga25s** [comment]
I'm still having this problem on version 2.0.13.

The issue appears when using PhpBrowser and REST at the same time:
```
$I->click("List all");
$I->see("Reviewed");
$I->see($I->getFormatedId($artworkJob['ArtworkJob']['id']));

$I->amGoingTo('View the artwork job');
$I->amOnPage($I->getCakeUrl(array('plugin' => 'artwork', 'controller' => 'artwork_jobs', 'action' => 'view', $artworkJob['ArtworkJob']['id'])));
$I->see($artworkJob['ArtworkJob']['name']);
$I->seeArtworkJobStatus($artworkJob['ArtworkJob']['id'], 'reviewed');

$I->sendPOST(
	$I->getCakeUrl(array('plugin' => 'artwork', 'controller' => 'artwork_jobs', 'action' => 'angular_rejectReview', 'ext' => 'json')),
	array( 'artwork_id' => $artworkJob['ArtworkJob']['id'] )
);
$I->seeResponseIsJson();
$I->seeResponseContainsJson(array('error' => false));
$I->see("The Review has been rejected");
```
StackTrace:
```
PHP Fatal error:  Call to a member function request() on a non-object in vendor/codeception/codeception/src/Codeception/Module/REST.php on line 389
PHP Stack trace:
PHP   1. {main}() vendor/codeception/codeception/codecept:0
PHP   2. Symfony\Component\Console\Application->run()vendor/codeception/codeception/codecept:27
PHP   3. Symfony\Component\Console\Application->doRun() vendor/symfony/console/Symfony/Component/Console/Application.php:126
PHP   4. Symfony\Component\Console\Application->doRunCommand()vendor/symfony/console/Symfony/Component/Console/Application.php:195
PHP   5. Symfony\Component\Console\Command\Command->run() /vendor/symfony/console/Symfony/Component/Console/Application.php:874
PHP   6. Codeception\Command\Run->execute() vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
PHP   7. Codeception\Command\Run->runSuites()vendor/codeception/codeception/src/Codeception/Command/Run.php:192
PHP   8. Codeception\Codecept->run() /vendor/codeception/codeception/src/Codeception/Command/Run.php:263
PHP   9. Codeception\Codecept->runSuite() vendor/codeception/codeception/src/Codeception/Codecept.php:156
PHP  10. Codeception\SuiteManager->run() vendor/codeception/codeception/src/Codeception/Codecept.php:173
PHP  11. Codeception\PHPUnit\Runner->doEnhancedRun() vendor/codeception/codeception/src/Codeception/SuiteManager.php:157
PHP  12. PHPUnit_Framework_TestSuite->run() vendor/codeception/codeception/src/Codeception/PHPUnit/Runner.php:100
PHP  13. PHPUnit_Framework_TestCase->run() vendor/phpunit/phpunit/src/Framework/TestSuite.php:722
PHP  14. PHPUnit_Framework_TestResult->run() vendor/phpunit/phpunit/src/Framework/TestCase.php:699
PHP  15. PHPUnit_Framework_TestCase->runBare() vendor/phpunit/phpunit/src/Framework/TestResult.php:609
PHP  16. PHPUnit_Framework_TestCase->runTest() vendor/phpunit/phpunit/src/Framework/TestCase.php:743
PHP  17. ReflectionMethod->invokeArgs() /vendor/phpunit/phpunit/src/Framework/TestCase.php:866
PHP  18. Codeception\TestCase\Cept->testCodecept() vendor/phpunit/phpunit/src/Framework/TestCase.php:866
PHP  19. require() vendor/codeception/codeception/src/Codeception/TestCase/Cept.php:64
PHP  20. FunctionalTester->sendPOST() app/Test/codeception/functional/004-ManageArtworkJobs/004-03-RejectComplexityByCaCept.php:31
PHP  21. Codeception\Scenario->runStep() app/Test/codeception/functional/FunctionalTester.php:2322
PHP  22. Codeception\TestCase\Cept->runStep() vendor/codeception/codeception/src/Codeception/Scenario.php:94
PHP  23. Codeception\Step->run() vendor/codeception/codeception/src/Codeception/TestCase/Shared/Actor.php:67
PHP  24. call_user_func_array() vendor/codeception/codeception/src/Codeception/Step.php:125
PHP  25. Codeception\Module\REST->sendPOST() /vendor/codeception/codeception/src/Codeception/Step.php:125
PHP  26. Codeception\Module\REST->execute() vendor/codeception/codeception/src/Codeception/Module/REST.php:223

Fatal error: Call to a member function request() on a non-object in vendor/codeception/codeception/src/Codeception/Module/REST.php on line 389
```
