### ISSUE TITLE
Laravel 5.2 support - issue with amLoggedAs

### ISSUE THREAD

**Issue by mabasic** [Codeception/Codeception#2658]
```
  [ErrorException] call_user_func_array() expects parameter 1 to be a valid callback, class 'Illuminate\Auth\SessionGuard' does not have a method 'driver'
```

[This function](https://github.com/Codeception/Codeception/blob/2.1/src/Codeception/Module/Laravel5.php#L627) should be: 

```
    public function amLoggedAs($user)
    {
        if ($user instanceof Authenticatable) {
            $this->app['auth']->setUser($user);
            return;
        }
        if (! $this->app['auth']->attempt($user)) {
            $this->fail("Failed to login with credentials " . json_encode($user));
        }
    }
```

Since there is not method `driver` in `Illuminate\Auth\SessionGuard`

Where should I open a PR for this?

**Comment by mabasic** [comment]
@janhenkgerritsen Great stuff!

**Comment by janhenkgerritsen** [comment]
Thanks for reporting this issue. I fixed it myself, because your solution did not take backwards compatability with Laravel < 5.2 into account, and you also removed the `$driver` parameter, which can also lead to backwards compatability issues.

**Comment by mabasic** [comment]
I know, that is why I didn't make a PR myself :smile:

**Comment by gandra** [comment]
I am using latest stable Codeception version 2.1.5.

I am still receiving error:
` [ErrorException] call_user_func_array() expects parameter 1 to be a valid callback, class 'Illuminate\Auth\SessionGuard' does not have a method 'driver'`  

with code:  
`$I->amLoggedAs($user);`

**Comment by mabasic** [comment]
They have to tag a new release for this to resolved.

**Comment by janhenkgerritsen** [comment]
Yes this fix will be available in 2.1.6, however, I don't know when it will be released. You could use the development branch of 2.1 by specifying 2.1.x-dev as your version for Composer if you really need this fix though.

**Comment by gandra** [comment]
Thanks. 
At the moment I have found workarround. In case I need it I  will try your suggestions.

**Comment by ssalama** [comment]
I think a $guard parameter should be added to `seeAuthentication` and `dontSeeAuthentication` methods.

**Comment by janhenkgerritsen** [comment]
@ssalama Why?

**Comment by ssalama** [comment]
@janhenkgerritsen In case if we needed to test if a user is authenticated by a non-default guard like `Auth::guard('admin')->check()`.
