### ISSUE TITLE
Unencoded html breaks report

### ISSUE THREAD

**Issue by mpgo13** [Codeception/Codeception#3819]
#### What are you trying to achieve?

One of my test contains a step like:

`$I->fillField($textArea, "... <script> ...");`

Running codecept with --html option should generate a well encoded report.

#### What do you get instead?

Actual result is a broken HTML report, containing the step as HTML code instead of encoded text (script tag breaks html)

### Details

Unrelated to the issue

**Comment by Naktibalda** [comment]
Fixed by #4175

**Comment by mpgo13** [comment]
Still a problem when passing html  to functions (in particular :

```

class HtmlCest
{
    private function login($username) { }
   
    public function testXSS()
    {
        $this->login("a<script>");
    }
}

```

Produces unencoded html report:
![image](https://user-images.githubusercontent.com/1078584/28143996-54faef96-67ac-11e7-8dc9-e893dae6ccf8.png)
