### ISSUE TITLE
Codeception SF4 service already initialized

### ISSUE THREAD

**Issue by hmonglee** [Codeception/Codeception#4806]
Hello,
I'm using Codeception in SF4 project.

Here my api.suite.yml :
```yml
actor: ApiTester
modules:
    enabled:
        - Symfony:
            app_path: src
            environment: test
            em_service: doctrine.orm.client_entity_manager
        - Doctrine2:
            depends: Symfony
            cleanup: true
        - REST:
            depends: Symfony
            part: Json
            url: 'http://localhost/api'
        - \Helper\Api
        - Asserts
```

When I launch my test I have this error : `[Symfony\Component\DependencyInjection\Exception\InvalidArgumentException] The "doctrine.orm.client_entity_manager" service is already initialized, you cannot replace it.`

If I try again, no error. If I remove the cache, same error the first time.

Thank you for the help.

**Comment by wslaghekke** [comment]
:+1:

**Comment by DzeryCZ** [comment]
Removing Doctrine configuration from `Functional.suite.yaml` solved the issue for me.

Just remove:
```
- Doctrine2:
            depends: Symfony
            cleanup: true
```

**Comment by Besedin86** [comment]
Have the same issue. Doctrine2 module depends by DataFactory module

**Comment by isd4n** [comment]
thanks @hmonglee. Waiting for the merge. @codeception team, when??

**Comment by DrummerKH** [comment]
Guys, any news on this issue. Makes my live harder. Can you please tell when it can be resolved?

**Comment by isd4n** [comment]
@DrummerKH you can use the phpunit from vendor while the issue is not resolved .

**Comment by isd4n** [comment]
@DrummerKH we're using the module db while the issue is not resolved.

**Comment by DrummerKH** [comment]
@isd4n we cannot use it because of we are using DataFactory which required to ORM.

**Comment by khienpc** [comment]
Have the same issue :(

**Comment by joelmedeiros** [comment]
Same issue here. 
My problem: 

`
suite.yml
       - Doctrine2:
            depends: Symfony
            cleanup: true
        - DataFactory:
            depends: Doctrine2
        - Symfony:
`

DataFactory depends on Doctrine2, I cannot remove it.

**Comment by khienpc** [comment]
I read `initializeContainer` method and guess the `debug` param can be a cause. 
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/Kernel.php#L447
Actually, I didn't find the root cause, but when I change `debug` param to `false` then it is working for now.

```
modules:
    enabled:
        - Symfony:
            app_path: 'src'
            environment: 'test'
            debug: false
        - Doctrine2:
            depends: Symfony
        - App\Tests\_support\Helper\Factories:
            depends: Doctrine2
            factories: tests/factories/definitions
        - REST:
            url: /api/
            depends: Symfony
        - App\Tests\_support\Helper\Functional
```

**Comment by joelmedeiros** [comment]
@khienpc it has worked for me. Thanks!

**Comment by DrummerKH** [comment]
Very strange, for me is not.

**Comment by Tobur** [comment]
For me too. It doesn't work change "debug to false"!

**Comment by Tobur** [comment]
Temporary and **ugly hack** for jenkins which allow me see build result on jenkins:

In my jenkins.sh
```
rm vendor/symfony/dependency-injection/Container.php
cp tests/_data/Container.php vendor/symfony/dependency-injection/
```

Where replaced file has replaced line 166:

```
        } elseif (isset($this->services[$id])) {
            return;
            //throw new InvalidArgumentException(sprintf('The "%s" service is already initialized, you cannot replace it.', $id));
        }
```
I commented exception and added return. It allow me to continue see green build on jenkins :-)

p.s. Don't use it, if so, remove it as soon as you get better solution for your CI.

**Comment by SamMousa** [comment]
> Guys, we are loving Codeception. But we still making changes in vendor path that it works. Please can you tell when it can be fixed. At first glance it doesn't look difficult.

Feel free to submit a PR!

**Comment by DrummerKH** [comment]
> > Guys, we are loving Codeception. But we still making changes in vendor path that it works. Please can you tell when it can be fixed. At first glance it doesn't look difficult.
> 
> Feel free to submit a PR!

Buy it was created already and closed. [https://github.com/Codeception/Codeception/pull/4952](PR)

**Comment by SamMousa** [comment]
It was closed by the creator because it was resolved by a configuration change.

**Comment by Tobur** [comment]
@SamMousa it's not resolved, creator of this pull request just removed at all Doctrine from your config.

**Comment by SamMousa** [comment]
I'm just stating that it was closed by the creator because his issue was resolved... Not that this issue is not valid..

**Comment by gdmfx** [comment]
@SamMousa can you please check the PR [#5262](https://github.com/Codeception/Codeception/pull/5262)

**Comment by Naktibalda** [comment]
Fixed by merging #5262
