### ISSUE TITLE
Module/Yii2 - Call to a member function stop() on null

### ISSUE THREAD

**Issue by olegkrivtsov** [Codeception/Codeception#5118]
#### What are you trying to achieve?

Running my functional tests. One of tests fails. I expect to see a failure message.

#### What do you get instead?

> Provide console output if related. Use `-vvv` mode for more details.

```bash
Codeception PHP Testing Framework v2.4.5
Powered by PHPUnit 7.1.5 by Sebastian Bergmann and contributors.

[1mFrontend\tests.functional Tests (1) [22m----------------------------------------------------------------
Modules: [32mFilesystem, Yii2[39m
----------------------------------------------------------------------------------------------------
[35;1mAboutCest:[39;22m Check about
Signature: [32mfrontend\tests\functional\AboutCest:checkAbout[39m
Test: [32mtests/functional/AboutCest.php:checkAbout[39m
[33mScenario --[39m
[36m  Destroying application[39m
[36m  Starting application[39m
[31;1m ERROR [39;22m

<pre>Exception &#039;Error&#039; with message &#039;Call to a member function stop() on null&#039; 

in /var/www/cms/vendor/codeception/base/src/Codeception/Module/Yii2.php:347

Stack trace:
#0 /var/www/cms/vendor/codeception/base/src/Codeception/Subscriber/Module.php(66): Codeception\Module\Yii2-&gt;_after(Object(Codeception\Test\Cest))
#1 /var/www/cms/vendor/symfony/event-dispatcher/EventDispatcher.php(212): Codeception\Subscriber\Module-&gt;after(Object(Codeception\Event\TestEvent), &#039;test.after&#039;, Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 /var/www/cms/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher-&gt;doDispatch(Array, &#039;test.after&#039;, Object(Codeception\Event\TestEvent))
#3 /var/www/cms/vendor/codeception/phpunit-wrapper/src/Listener.php(133): Symfony\Component\EventDispatcher\EventDispatcher-&gt;dispatch(&#039;test.after&#039;, Object(Codeception\Event\TestEvent))
#4 /var/www/cms/vendor/codeception/phpunit-wrapper/src/Listener.php(119): Codeception\PHPUnit\Listener-&gt;fire(&#039;test.after&#039;, Object(Codeception\Event\TestEvent))
#5 /var/www/cms/vendor/phpunit/phpunit/src/Framework/TestResult.php(384): Codeception\PHPUnit\Listener-&gt;endTest(Object(Codeception\Test\Cest), 0)
#6 /var/www/cms/vendor/codeception/base/src/Codeception/Test/Test.php(111): PHPUnit\Framework\TestResult-&gt;endTest(Object(Codeception\Test\Cest), 0)
#7 /var/www/cms/vendor/phpunit/phpunit/src/Framework/TestSuite.php(776): Codeception\Test\Test-&gt;run(Object(PHPUnit\Framework\TestResult))
#8 /var/www/cms/vendor/codeception/phpunit-wrapper/src/Runner.php(114): PHPUnit\Framework\TestSuite-&gt;run(Object(PHPUnit\Framework\TestResult))
#9 /var/www/cms/vendor/codeception/base/src/Codeception/SuiteManager.php(157): Codeception\PHPUnit\Runner-&gt;doEnhancedRun(Object(Codeception\Suite), Object(PHPUnit\Framework\TestResult), Array)
#10 /var/www/cms/vendor/codeception/base/src/Codeception/Codecept.php(189): Codeception\SuiteManager-&gt;run(Object(Codeception\PHPUnit\Runner), Object(PHPUnit\Framework\TestResult), Array)
#11 /var/www/cms/vendor/codeception/base/src/Codeception/Codecept.php(158): Codeception\Codecept-&gt;runSuite(Array, &#039;functional&#039;, NULL)
#12 /var/www/cms/vendor/codeception/base/src/Codeception/Command/Run.php(466): Codeception\Codecept-&gt;run(&#039;functional&#039;)
#13 /var/www/cms/vendor/codeception/base/src/Codeception/Command/Run.php(361): Codeception\Command\Run-&gt;runSuites(Array, Array)
#14 /var/www/cms/vendor/symfony/console/Command/Command.php(251): Codeception\Command\Run-&gt;execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/cms/vendor/symfony/console/Application.php(886): Symfony\Component\Console\Command\Command-&gt;run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/cms/vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application-&gt;doRunCommand(Object(Codeception\Command\Run), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/cms/vendor/symfony/console/Application.php(145): Symfony\Component\Console\Application-&gt;doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/cms/vendor/codeception/base/src/Codeception/Application.php(108): Symfony\Component\Console\Application-&gt;run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/cms/vendor/codeception/base/codecept(42): Codeception\Application-&gt;run()
#20 {main}</pre>PHP Fatal error:  Uncaught RuntimeException: Command Did Not Finish Properly in /var/www/cms/vendor/codeception/base/src/Codeception/Subscriber/ErrorHandler.php:101
Stack trace:
#0 [internal function]: Codeception\Subscriber\ErrorHandler->shutdownHandler()
#1 {main}
  thrown in /var/www/cms/vendor/codeception/base/src/Codeception/Subscriber/ErrorHandler.php on line 101
```
> Provide test source code if related

In the `Module/Yii2.php` line 347:

```php
$this->connectionWatcher->stop();
$this->connectionWatcher->closeAll();
unset($this->connectionWatcher);
```
### Details

* Codeception version: 2.4.5
* PHP Version: 7.2
* Operating System: Ubuntu 18.04
* Installation type: Composer
* List of installed packages (`composer show`)

```
2amigos/yii2-date-picker-widget       1.0.7              Bootstrap DatePicker widget for Yii2.
2amigos/yii2-file-upload-widget       1.0.8              Blueimp file upload widget for the Y...
2amigos/yii2-gallery-widget           1.1.0              Blueimp gallery widget for the Yii f...
2amigos/yii2-select2-widget           0.1.2              Select 2 jQuery plugin for Yii2 with...
almasaeed2010/adminlte                v2.4.8             AdminLTE - admin control panel and d...
aws/aws-sdk-php                       3.64.8             AWS SDK for PHP - Use Amazon Web Ser...
behat/gherkin                         v4.5.1             Gherkin DSL parser for PHP 5.3
bower-asset/blueimp-canvas-to-blob    v3.14.0           
bower-asset/blueimp-file-upload       v9.22.0           
bower-asset/blueimp-gallery           v2.17.0           
bower-asset/blueimp-load-image        v2.19.0           
bower-asset/blueimp-tmpl              v3.11.0           
bower-asset/bootstrap                 v3.3.7            
bower-asset/bootstrap-datepicker      v1.7.0            
bower-asset/inputmask                 3.3.11            
bower-asset/jquery                    3.2.1             
bower-asset/jquery-ui                 1.12.1            
bower-asset/lightbox2                 2.7.1             
bower-asset/punycode                  v1.3.2            
bower-asset/select2                   4.0.5             
bower-asset/select2-bootstrap-theme   0.1.0-beta.10     
bower-asset/typeahead.js              v0.11.1           
bower-asset/yii2-pjax                 2.0.7.1           
branchonline/yii2-lightbox            v1.2.0             Lightbox widget for Yii2
cebe/markdown                         1.1.2              A super fast, highly extensible mark...
cebe/yii2-gravatar                    1.1                Gravatar Widget for Yii 2
codeception/base                      2.4.5              BDD-style testing framework
codeception/phpunit-wrapper           7.2.0              PHPUnit classes used by Codeception
codeception/stub                      2.0.4              Flexible Stub wrapper for PHPUnit's ...
codeception/verify                    1.0.0              BDD assertion library for PHPUnit
composer/installers                   v1.5.0             A multi-framework Composer library i...
cornernote/yii2-linkall               1.0.0              Behavior to handle saving multiple m...
dmstr/yii2-adminlte-asset             2.6.2              AdminLTE backend theme asset bundle ...
dnoegel/php-xdg-base-dir              0.1                implementation of xdg base directory...
doctrine/instantiator                 1.1.0              A small, lightweight utility to inst...
ezyang/htmlpurifier                   v4.10.0            Standards compliant HTML filter writ...
facebook/webdriver                    1.6.0              A PHP client for Selenium WebDriver
fortawesome/font-awesome              v4.7.0             The iconic font and CSS framework
frostealth/yii2-aws-s3                v2.1.1             An Amazon S3 component for Yii2
fzaninotto/faker                      v1.8.0             Faker is a PHP library that generate...
guzzlehttp/guzzle                     6.3.3              Guzzle is a PHP HTTP client library
guzzlehttp/promises                   v1.3.1             Guzzle promises library
guzzlehttp/psr7                       1.4.2              PSR-7 message implementation that al...
imagine/imagine                       v0.7.1             Image processing for PHP 5.3
jakub-onderka/php-console-color       0.1               
jakub-onderka/php-console-highlighter v0.3.2            
kartik-v/yii2-krajee-base             v1.8.9             Base library and foundation componen...
kartik-v/yii2-sortable                v1.2.0             Create sortable lists and grids usin...
mtdowling/jmespath.php                2.4.0              Declaratively specify how to extract...
myclabs/deep-copy                     1.8.1              Create deep copies (clones) of your ...
nikic/php-parser                      v3.1.5             A PHP parser written in PHP
oonne/yii2-sortable-grid-view         1.0.0              Yii2 GridView widget base on jQuery ...
phar-io/manifest                      1.0.1              Component for reading phar.io manife...
phar-io/version                       1.0.1              Library for handling version informa...
phpdocumentor/reflection-common       1.0.1              Common reflection classes used by ph...
phpdocumentor/reflection-docblock     4.3.0              With this component, a library can p...
phpdocumentor/type-resolver           0.4.0             
phpspec/php-diff                      v1.1.0             A comprehensive library for generati...
phpspec/prophecy                      1.8.0              Highly opinionated mocking framework...
phpunit/php-code-coverage             6.0.5              Library that provides collection, pr...
phpunit/php-file-iterator             1.4.5              FilterIterator implementation that f...
phpunit/php-text-template             1.2.1              Simple template engine.
phpunit/php-timer                     2.0.0              Utility class for timing
phpunit/php-token-stream              3.0.0              Wrapper around PHP's tokenizer exten...
phpunit/phpunit                       7.1.5              The PHP Unit Testing framework.
phpunit/phpunit-mock-objects          6.1.2              Mock Object library for PHPUnit
psr/http-message                      1.0.1              Common interface for HTTP messages
psy/psysh                             v0.8.18            An interactive shell for modern PHP.
rmrevin/yii2-fontawesome              2.17.1             Asset Bundle for Yii2 with Font Awesome
sebastian/code-unit-reverse-lookup    1.0.1              Looks up which function or method a ...
sebastian/comparator                  3.0.2              Provides the functionality to compar...
sebastian/diff                        3.0.1              Diff implementation
sebastian/environment                 3.1.0              Provides functionality to handle HHV...
sebastian/exporter                    3.1.0              Provides the functionality to export...
sebastian/global-state                2.0.0              Snapshotting of global state
sebastian/object-enumerator           3.0.3              Traverses array structures and objec...
sebastian/object-reflector            1.1.1              Allows reflection of object attribut...
sebastian/recursion-context           3.0.0              Provides functionality to recursivel...
sebastian/resource-operations         1.0.0              Provides a list of PHP built-in func...
sebastian/version                     2.0.1              Library that helps with managing the...
swiftmailer/swiftmailer               v5.4.12            Swiftmailer, free feature-rich PHP m...
symfony/browser-kit                   v4.1.3             Symfony BrowserKit Component
symfony/console                       v4.1.3             Symfony Console Component
symfony/css-selector                  v4.1.3             Symfony CssSelector Component
symfony/dom-crawler                   v4.1.3             Symfony DomCrawler Component
symfony/event-dispatcher              v4.1.3             Symfony EventDispatcher Component
symfony/finder                        v4.1.3             Symfony Finder Component
symfony/polyfill-ctype                v1.9.0             Symfony polyfill for ctype functions
symfony/polyfill-mbstring             v1.9.0             Symfony polyfill for the Mbstring ex...
symfony/polyfill-php72                v1.9.0             Symfony polyfill backporting some PH...
symfony/process                       v4.1.3             Symfony Process Component
symfony/var-dumper                    v4.1.3             Symfony mechanism for exploring and ...
symfony/yaml                          v4.1.3             Symfony Yaml Component
theseer/tokenizer                     1.1.0              A small library for converting token...
thrieu/yii2-grid-view-state           dev-master e53e89d Save filters from GridView to sessio...
vova07/yii2-imperavi-widget           2.0.5              The imperavi redactor widget for Yii...
webmozart/assert                      1.3.0              Assertions to validate method input/...
yiidoc/yii2-redactor                  2.0.1              Extension redactor for Yii2 Framework.
yiimaker/yii2-social-share            v2.2.0             Extension for sharing on social netw...
yiisoft/yii2                          2.0.15.1           Yii PHP Framework Version 2
yiisoft/yii2-bootstrap                2.0.8              The Twitter Bootstrap extension for ...
yiisoft/yii2-composer                 2.0.7              The composer plugin for Yii extensio...
yiisoft/yii2-debug                    2.0.13             The debugger extension for the Yii f...
yiisoft/yii2-faker                    2.0.4              Fixture generator. The Faker integra...
yiisoft/yii2-gii                      2.0.7              The Gii extension for the Yii framework
yiisoft/yii2-imagine                  2.1.1              The Imagine integration for the Yii ...
yiisoft/yii2-jui                      2.0.7              The Jquery UI extension for the Yii ...
yiisoft/yii2-queue                    2.1.0              Yii2 Queue Extension which supported...
yiisoft/yii2-shell                    2.0.1              The interactive shell extension for ...
yiisoft/yii2-swiftmailer              2.0.7              The SwiftMailer integration for the ...
```

* Suite configuration:

```yml
namespace: frontend\tests
actor_suffix: Tester
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
modules:
    config:
        Yii2:
            configFile: 'config/codeception-local.php'
```

**Comment by yurii-github** [comment]
faced this stuff today

I guess you were trying to test console app, right?

Hotfix would be to add to your main.config.php
`'class' => \yii\console\Application::class,`

Thing is, test module assumes  \yii\web\Application by default at https://github.com/Codeception/Codeception/blob/2.4/src/Codeception/Lib/Connector/Yii2.php#L108

so it silently fails with "Unable to determine the entry script file path."

Also, codeception config should be something like

```
actor: UnitTester
bootstrap: bootstrap.php
modules:
    enabled:
        - Yii2
        - Asserts
        - \common\Helper\Unit

    config:
        Yii2:
            configFile: 'tests/config-test.php'
```

regards

**Comment by Eseperio** [comment]
Same here. Not console app. Trying to figure out why. The functional tests worked before ( a few months ago)

**Comment by Eseperio** [comment]
In my case the yii2 codeception module event `_before` is not triggering. So no connection object is created.

**Comment by niebylem** [comment]
This exception is not helpfull at all. I see that we all had different cause of throwing it. In my case the problem was dependency injection:
`Yii::$container->set('classToReplace','classToInject')`
But it was thrown only while I launched more than one test case.

I figured out that I have this error also while running console tests, and setting 'application class' in config didn't solve it but actually it's not essential for me.

**Comment by gijsstegehuis** [comment]
This seems to have been fixed in https://github.com/Codeception/Codeception/pull/5136

**Comment by vercotux** [comment]
I'm still getting this even after #5136. No idea what's causing it because the errors are not revealing anything useful apart from the script file name where it happens.

**Comment by Eseperio** [comment]
Still an issue. Keeps failing silently, this time in the _after method, but no clues about what can be happening. ¿Anyone more 
or am i alone?
